FROM node:18-alpine AS builder

WORKDIR /app/frontend
COPY project/frontend/package*.json ./
RUN npm install
COPY project/frontend .
RUN npm run build

FROM node:18-alpine
WORKDIR /app/frontend
COPY --from=builder /app/frontend ./

EXPOSE 3000
CMD ["npm", "start"]

